server.port=8082
server.address=0.0.0.0
spring.application.name=frontend-service
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
quiz-service.url=http://localhost:8080
game-service.url=http://localhost:8081
game-service.ws-url=http://localhost:8081
