server:
  port: 8080

spring:
  application:
    name: quiz-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: false
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 2s

  mail:
    host: smtp.gmail.com
    port: 587
    username: elizark777@gmail.com
    password: aahyvugymfgptayg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: bXlTdXBlclNlY3JldEtleUZvckpXVFRva2VuR2VuZXJhdGlvbjEyMw==
  expiration-ms: 86400000

app:
  frontend-base-url: ${FRONTEND_BASE_URL:http://localhost:8082}
  invite-token-ttl-hours: ${INVITE_TTL_HOURS:72}
  mail:
    enabled: true

